name: trafficutilities
description: Traffic Utilties v3

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.0+5
  firebase_auth: ^0.11.1+6
  firebase_database: ^3.0.2
  cloud_firestore: ^0.12.5+1
  animated_text_kit: ^1.3.1
  modal_progress_hud: ^0.1.3
  flutter_webview_plugin: ^0.3.5
  date_format: ^1.0.6
  google_sign_in: ^4.0.2

  rxdart: ^0.22.0
  google_maps_flutter: ^0.5.19+2
  #geoflutterfire: ^2.0.3+5
  location: ^2.3.5

  font_awesome_flutter: ^8.4.0
  datetime_picker_formfield: ^0.2.0
  flutter_launcher_icons: ^0.7.2+1


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/logo.png"

flutter:

  uses-material-design: true

  assets:
    - images/
